[package]
name = "mips_int"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions At https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.3.0"
byteorder = "1.4.3"
regex = "1.5.4"