name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: rustup toolchain install nightly-2022-01-11 --force
    - name: Build
      run: cargo +nightly build --verbose
    - name: Run tests
      run: cargo +nightly test --verbose
